Repository glotzerlab/signac-flow, pull requests merged in 2019-08, with the labels that each got.

#124 Make environments opt-out
  changelog.txt
  flow/__init__.py
  flow/util/config.py
Labels: enhancement

#130 Fix/issue-129 test project
  changelog.txt
  flow/__init__.py
  flow/template.py
  flow/templates/project_testing.pyt
  flow/testing.py
Labels: enhancement

#110 Implement optional statistical profiling for status command.
  changelog.txt
  flow/project.py
  flow/util/config.py
Labels: enhancement

#143 Resolve issue #142 by fixing error with zero jobs.
  flow/project.py
Labels: bug

#101 Fix summit multigpu
  changelog.txt
  flow/environments/incite.py
  tests/template_reference_data.tar.gz
Labels: bug, expertise-needed

#137 Add pre/post conditions to API documentation.
  doc/api.rst
  flow/project.py
Labels: documentation
