Repository glotzerlab/signac-flow, pull requests merged in 2020-09, with the labels that each got.

#348 Add aggregator classes in flow
  flow/aggregates.py
  tests/test_aggregates.py
Labels: GSoC, aggregation

#351 Fix hashing of aggregate classes, rename reverse_order to sort_ascending
  flow/aggregates.py
  tests/test_aggregates.py
Labels: aggregation, bug

#342 Modify node counting from resource sets for serial execution.
  changelog.txt
  flow/environments/incite.py
  flow/templates/summit.sh
Labels: cluster submission, enhancement

#283 Add a class for Directives
  changelog.txt
  flow/directives.py
  flow/environment.py
  flow/errors.py
  flow/project.py
  tests/test_directives.py
  tests/test_project.py
  tests/test_templates.py
Labels: GSoC, directives, enhancement

#354 Fix performance regression in job submission.
  changelog.txt
  flow/project.py
Labels: bug, cluster submission
