Repository glotzerlab/signac-flow, pull requests merged in 2020-06, with the labels that each got.

#294 Fix incite node counting logic.
  changelog.txt
  flow/environments/incite.py
Labels: bug, cluster submission

#279 Show expected exec commands in submission script.
  flow/project.py
  flow/templates/base_script.sh
  tests/define_template_test_project.py
  tests/generate_template_reference_data.py
  tests/template_reference_data.tar.gz
Labels: cluster submission, enhancement, groups

#297 Remove parallel option for FlowGroup submission
  flow/project.py
  tests/template_reference_data.tar.gz
  tests/test_project.py
Labels: groups

#303 Fix Test Warnings
  flow/project.py
Labels: bug, cluster submission, groups
