Repository glotzerlab/signac-flow, pull requests merged in 2021-01, with the labels that each got.

#409 Evaluate directives in _JobOperation Constructor
  changelog.txt
  flow/project.py
  tests/test_project.py
Labels: bug, directives

#416 Unify group/aggregate selection
  flow/aggregates.py
  flow/project.py
  tests/template_reference_data.tar.gz
  tests/test_project.py
Labels: refactor

#425 Deprecate unbuffered mode
  changelog.txt
  flow/project.py
  tests/test_project.py
Labels: enhancement

#426 Refactoring tasks
  changelog.txt
  doc/api.rst
  flow/environment.py
  flow/project.py
  flow/render_status.py
  flow/scheduling/base.py
  flow/scheduling/fake_scheduler.py
  flow/scheduling/lsf.py
  flow/scheduling/simple_scheduler.py
  flow/scheduling/slurm.py
  flow/scheduling/status.py
  flow/scheduling/torque.py
  flow/template.py
  flow/templates/base_status.jinja
  flow/util/template_filters.py
  tests/test_project.py
Labels: refactor

#422 Refactor aggregation
  flow/aggregates.py
  flow/project.py
  tests/test_aggregates.py
Labels: aggregation, refactor

#417 New _fetch_status code.
  changelog.txt
  flow/project.py
  flow/templates/base_status.jinja
  flow/util/misc.py
  tests/define_test_project.py
  tests/generate_template_reference_data.py
  tests/template_reference_data.tar.gz
  tests/test_project.py
  tests/test_templates.py
Labels: aggregation, enhancement, refactor

#427 Next: Refactor internals to support aggregation, improved performance and documentation.
  .circleci/config.yml
  .gitignore
  bin/simple-scheduler
  changelog.txt
  doc/api.rst
  doc/conf.py
  flow/__init__.py
  flow/__main__.py
  flow/aggregates.py
  flow/directives.py
  flow/environment.py
  flow/environments/incite.py
  flow/environments/umich.py
  flow/environments/xsede.py
  flow/errors.py
  flow/labels.py
  flow/operations.py
  flow/project.py
  flow/render_status.py
  flow/scheduling/__init__.py
  flow/scheduling/base.py
  flow/scheduling/fake_scheduler.py
  flow/scheduling/fakescheduler.py
  flow/scheduling/lsf.py
  flow/scheduling/simple_scheduler.py
  flow/scheduling/slurm.py
  flow/scheduling/status.py
  flow/scheduling/torque.py
  flow/template.py
  flow/templates/base_status.jinja
  flow/testing.py
  flow/util/__init__.py
  flow/util/config.py
  flow/util/misc.py
  flow/util/template_filters.py
  flow/util/translate.py
  flow/version.py
  requirements.txt
  setup.cfg
  tests/define_test_project.py
  tests/generate_template_reference_data.py
  tests/generate_template_review_document.py
  tests/template_reference_data.tar.gz
  tests/test_aggregates.py
  tests/test_directives.py
  tests/test_project.py
  tests/test_templates.py
  tests/test_util.py
Labels: aggregation, enhancement

#434 Fix jinja templates for status output.
  flow/project.py
  flow/templates/base_status.jinja
  flow/templates/base_status_compact.jinja
  flow/templates/base_status_expand.jinja
  flow/templates/base_status_stack.jinja
Labels: bug

#438 Fix _call_submit signature.
  flow/scheduling/base.py
Labels: bug
