Repository glotzerlab/signac-flow, pull requests merged in 2021-04, with the labels that each got.

#486 Change default status_parallelization to "none".
  changelog.txt
  flow/project.py
  flow/util/config.py
  flow/util/misc.py
Labels: bug

#484 Default memory requests to integer values
  changelog.txt
  flow/directives.py
  flow/project.py
  flow/templates/lsf.sh
  flow/templates/slurm.sh
  flow/templates/torque.sh
  flow/util/template_filters.py
  tests/template_reference_data.tar.gz
  tests/test_project.py
Labels: bug, directives

#491 Changed TORQUE to PBS
  changelog.txt
  contributors.yaml
  doc/api.rst
  doc/supported_environments.rst
  doc/supported_environments/pbs.rst
  doc/supported_environments/torque.rst
  flow/environment.py
  flow/scheduling/pbs.py
  flow/templates/pbs.sh
Labels: cluster submission, refactor

#488 Add submission summary feature.
  changelog.txt
  flow/project.py
  flow/templates/base_status.jinja
Labels: cluster submission, enhancement

#487 Remove FlowProject.add_operation
  changelog.txt
  doc/api.rst
  flow/project.py
Labels: bug

#496 Enforce Operation Requirements
  changelog.txt
  flow/project.py
  tests/test_project.py
Labels: enhancement

#503 Only write known JobStatus values.
  changelog.txt
  flow/project.py
  tests/test_project.py
Labels: cluster submission, enhancement

#501 Fix --only-incomplete-operations, expand basic info in status overview
  changelog.txt
  flow/project.py
  flow/render_status.py
  flow/templates/base_status.jinja
Labels: cluster submission, enhancement
