Repository glotzerlab/signac-flow, pull requests merged in 2021-05, with the labels that each got.

#495 Improve jinja template readability.
  changelog.txt
  flow/project.py
  flow/template.py
  flow/templates/base_script.sh
  flow/templates/base_status.jinja
  flow/templates/base_status_compact.jinja
  flow/templates/base_status_expand.jinja
  flow/templates/base_status_stack.jinja
  flow/templates/bridges2.sh
  flow/templates/comet.sh
  flow/templates/lsf.sh
  flow/templates/pbs.sh
  flow/templates/simple_scheduler.sh
  flow/templates/slurm.sh
  flow/templates/stampede2.sh
  flow/templates/summit.sh
  flow/templates/umich-greatlakes.sh
Labels: refactor

#464 Enable Aggregate Operation
  doc/api.rst
  flow/__init__.py
  flow/aggregates.py
  flow/operations.py
  flow/project.py
  flow/templates/base_status.jinja
  tests/define_aggregate_test_project.py
  tests/test_aggregates.py
  tests/test_project.py
Labels: aggregation

#518 Fix: don't catch SubmitErrors, show to user.
  changelog.txt
  flow/project.py
  flow/util/misc.py
  tests/test_project.py
Labels: bug, cluster submission

#500 Add Andes template and environment
  changelog.txt
  doc/supported_environments.rst
  doc/supported_environments/andes.rst
  flow/environments/incite.py
  flow/templates/andes.sh
  tests/generate_template_reference_data.py
  tests/template_reference_data.tar.gz
Labels: enhancement

#502 Add operation.with_directives decorator
  changelog.txt
  doc/api.rst
  flow/directives.py
  flow/environments/incite.py
  flow/operations.py
  flow/project.py
  tests/define_directives_test_project.py
  tests/define_template_test_project.py
  tests/define_test_project.py
  tests/test_project.py
Labels: directives, enhancement
