Repository glotzerlab/signac-flow, pull requests merged in 2021-06, with the labels that each got.

#535 Sort directives for consistency with other docs.
  flow/directives.py
  flow/environment.py
Labels: documentation

#533 Require a scheduler to submit, even with --pretend enabled.
  changelog.txt
  flow/project.py
  tests/test_project.py
Labels: cluster submission, enhancement

#531 Fixed dependency flag
  changelog.txt
  flow/scheduling/slurm.py
  tests/test_project.py
Labels: bug, cluster submission

#542 Refactor aggregates cursors.
  changelog.txt
  flow/aggregates.py
  flow/project.py
  tests/define_aggregate_test_project.py
  tests/test_project.py
Labels: refactor
