Repository glotzerlab/signac-flow, pull requests merged in 2022-03, with the labels that each got.

#614 Fix: tqdm.auto requires ipywidgets for notebook support.
  .circleci/ci-oldest-reqs.txt
  changelog.txt
  flow/project.py
  flow/render_status.py
  flow/util/misc.py
  requirements.txt
  setup.py
Labels: bug

#624 Merge requirements-dev and requirements-precommit and removed pre-checks
  .circleci/config.yml
  contributors.yaml
  doc/support.rst
  requirements/requirements-dev.txt
  requirements/requirements-precommit.txt
Labels: enhancement

#615 Make utilities private methods/classes.
  changelog.txt
  flow/project.py
  flow/util/misc.py
  tests/test_project.py
Labels: enhancement, refactor

#627 Change hook trigger names
  changelog.txt
  flow/hooks/hooks.py
  flow/project.py
  tests/define_hooks_install.py
  tests/define_hooks_test_project.py
  tests/template_reference_data.tar.gz
  tests/test_project.py
Labels: enhancement, hooks

#628 Require Python 3.8+.
  .circleci/ci-oldest-reqs.txt
  .circleci/config.yml
  .pre-commit-config.yaml
  changelog.txt
  doc/installation.rst
  flow/project.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: enhancement
